In [15]:
import pandas as pd
import numpy as np
from keras.models import load_model
from keras.utils import pad_sequences
import ast  

In [16]:
loaded_array1 = np.load('prediction.npy')

In [17]:
loaded_array1.shape

(1, 34875)

In [18]:
transformed = loaded_array1.flatten()
transformed

array([ 0.48704965,  0.2450913 , -0.00298166, ...,  0.5001052 ,
        0.93288397, -0.00940523])

In [19]:
transformed.shape

(34875,)

In [20]:
transformed.size

34875

In [21]:
targetlength=transformed.size
reshaped_array = transformed.reshape((int(targetlength/3), 3))
reshaped_array

array([[ 0.48704965,  0.2450913 , -0.00298166],
       [ 0.49126851,  0.21385351, -0.02025694],
       [ 0.48448595,  0.2253867 , -0.01975816],
       ...,
       [ 0.49277447,  0.93055559, -0.01087147],
       [ 0.49618886,  0.93728434, -0.00347037],
       [ 0.5001052 ,  0.93288397, -0.00940523]])

In [22]:
reshaped_array[-9:]

array([[ 0.5216233 ,  0.91741873, -0.00366002],
       [ 0.49547728,  0.89650364, -0.00572195],
       [ 0.50883264,  0.92386661, -0.0082283 ],
       [ 0.51253621,  0.92615087, -0.00211732],
       [ 0.51161159,  0.93250826, -0.00906901],
       [ 0.48033549,  0.9062722 , -0.01240113],
       [ 0.49277447,  0.93055559, -0.01087147],
       [ 0.49618886,  0.93728434, -0.00347037],
       [ 0.5001052 ,  0.93288397, -0.00940523]])

In [23]:
reshaped_array.shape

(11625, 3)

In [24]:
import pandas as pd
prefix_face = "face"
face_coor = 80
prefix_pose = "pose"
pose_coor = 33
prefix_left_hand = "left_hand"
prefix_right_hand = "right_hand"
hand_coor = 21

framenumber  = 0
coor_per_frame = 155
maximumframe = int(targetlength/465)
maximumframe

75

In [25]:
df = pd.DataFrame()
counter = 0
for i in range(maximumframe):
    #face
    counter = 0
    column_name_x=f'{prefix_face}{i}_x'
    column_name_y=f'{prefix_face}{i}_y'
    column_name_z=f'{prefix_face}{i}_z'
    df[column_name_x]=None
    df[column_name_y]=None
    df[column_name_z]=None
    for j in range(i*coor_per_frame,i*coor_per_frame+face_coor):
        df.loc[counter, column_name_x] = reshaped_array[j,0]
        df.loc[counter, column_name_y] = reshaped_array[j,1]
        df.loc[counter, column_name_z] = reshaped_array[j,2]
        counter=counter+1

    #pose
    column_name_x=f'{prefix_pose}{i}_x'
    column_name_y=f'{prefix_pose}{i}_y'
    column_name_z=f'{prefix_pose}{i}_z'
    df[column_name_x]=None
    df[column_name_y]=None
    df[column_name_z]=None
    counter = 0
    for k in range(i*coor_per_frame+face_coor,i*coor_per_frame+face_coor+pose_coor):
        df.loc[counter, column_name_x] = reshaped_array[k,0]
        df.loc[counter, column_name_y] = reshaped_array[k,1]
        df.loc[counter, column_name_z] = reshaped_array[k,2]
        counter=counter+1
        
    #left hand
    column_name_x=f'{prefix_left_hand}{i}_x'
    column_name_y=f'{prefix_left_hand}{i}_y'
    column_name_z=f'{prefix_left_hand}{i}_z'
    df[column_name_x]=None
    df[column_name_y]=None
    df[column_name_z]=None
    counter = 0
    for m in range(i*coor_per_frame+face_coor+pose_coor,i*coor_per_frame+face_coor+pose_coor+hand_coor):
        df.loc[counter, column_name_x] = reshaped_array[m,0]
        df.loc[counter, column_name_y] = reshaped_array[m,1]
        df.loc[counter, column_name_z] = reshaped_array[m,2]
        counter=counter+1

    #right hand
    column_name_x=f'{prefix_right_hand}{i}_x'
    column_name_y=f'{prefix_right_hand}{i}_y'
    column_name_z=f'{prefix_right_hand}{i}_z'
    df[column_name_x]=None
    df[column_name_y]=None
    df[column_name_z]=None
    counter = 0
    for n in range(i*coor_per_frame+face_coor+pose_coor+hand_coor,i*coor_per_frame+face_coor+pose_coor+hand_coor+hand_coor):
        df.loc[counter, column_name_x] = reshaped_array[n,0]
        df.loc[counter, column_name_y] = reshaped_array[n,1]
        df.loc[counter, column_name_z] = reshaped_array[n,2]
        counter=counter+1
        
        
#print(df["face0_x"])
df.to_csv('output.csv', index=False)

C:\Users\a1964\AppData\Local\Temp\ipykernel_1852\1640207084.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name_y]=None
C:\Users\a1964\AppData\Local\Temp\ipykernel_1852\1640207084.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name_z]=None
C:\Users\a1964\AppData\Local\Temp\ipykernel_1852\1640207084.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.co